pipenv install cookiecutter
pipenv install ipykernel
pipenv install _ipyw_jlab_nb_ext_conf
pipenv install _nb_ext_conf
pipenv install numpy
pipenv install pandas
pipenv install statsmodels
pipenv install sklearn
pipenv install matplotlib
pipenv install seaborn
pipenv install bokeh
pipenv install beautifulsoup4
pipenv install lxml
pipenv install bkcharts
pipenv install curl
pipenv install cython
pipenv install dask
pipenv install dask-core
pipenv install dask-glm
pipenv install dask-ml
pipenv install dask-searchcv
pipenv install datashader
pipenv install fiona
pipenv install flake8
pipenv install gdal
pipenv install gensim
pipenv install geos
pipenv install glob
pipenv install holoviews
pipenv install keras
pipenv install keras-gpu
pipenv install nose
pipenv install numba
pipenv install numpydoc
pipenv install opencv
pipenv install pep8
pipenv install plotly
pipenv install portpicker
pipenv install proj4
pipenv install pyflakes
pipenv install pylint
pipenv install pytest
pipenv install pytorch
pipenv install requests
pipenv install tensorflow
pipenv install scipy
pipenv install scrapy
pipenv install shapely
pipenv install nltk
pipenv install alabaster
cookiecutter https://github.com/drivendata/cookiecutter-data-science
